/**
 * FirebasePostsRepository.kt
 * ===========================
 * This is the Firebase implementation of PostsRepository.
 * It handles reading and creating promotional/news posts in Firestore.
 *
 * KEY CONCEPTS FOR BEGINNERS:
 * ---------------------------
 * 1. SIMPLE CRUD: This repository only supports Create and Read.
 *    No update or delete - posts are meant to be permanent (for now).
 *
 * 2. REAL-TIME POSTS: When an admin creates a post, all users
 *    viewing the posts list will see it appear automatically.
 *
 * FIRESTORE COLLECTION: "posts"
 */
package com.example.drivewise.Data.remote

import com.example.drivewise.domain.model.Post
import com.example.drivewise.domain.repository.PostsRepository
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.Query
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await

/**
 * Firebase Firestore implementation of PostsRepository.
 *
 * Manages the "posts" collection in Firestore.
 *
 * @param firestore The Firestore database instance
 */
class FirebasePostsRepository(
    private val firestore: FirebaseFirestore
) : PostsRepository {

    /**
     * Reference to the "posts" collection.
     */
    private val postsCollection get() = firestore.collection("posts")

    // ═══════════════════════════════════════════════════════════════════════════
    // OBSERVE POSTS (REAL-TIME)
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * Observes all posts with real-time updates.
     *
     * Posts are sorted by createdAt (newest first).
     * Both admins and clients can view posts.
     *
     * @return Flow emitting all posts whenever any post changes
     */
    override fun observePosts(): Flow<List<Post>> = callbackFlow {
        // Set up real-time listener, sorted by creation date (newest first)
        val registration = postsCollection
            .orderBy("createdAt", Query.Direction.DESCENDING)
            .addSnapshotListener { snapshot, error ->
                if (error != null) {
                    close(error)
                    return@addSnapshotListener
                }

                // Convert Firestore documents to Post objects
                val posts = snapshot?.documents?.mapNotNull { doc ->
                    doc.toObject(Post::class.java)?.copy(id = doc.id)
                }.orEmpty()

                // Emit the posts list
                trySend(posts)
            }

        // Clean up when Flow is cancelled
        awaitClose { registration.remove() }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // CREATE POST
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * Creates a new post.
     *
     * Only admins should call this (enforced at UI level).
     * The post ID is auto-generated by Firestore.
     *
     * @param post The post to create (id will be auto-generated)
     * @return Result.success if created successfully
     */
    override suspend fun createPost(post: Post): Result<Unit> = runCatching {
        // Create a new document reference with auto-generated ID
        val doc = postsCollection.document()

        // Save the post with the auto-generated ID included in the data
        postsCollection.document(doc.id).set(post.copy(id = doc.id)).await()
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // GET SINGLE POST
    // ═══════════════════════════════════════════════════════════════════════════

    /**
     * Fetches a single post by ID.
     *
     * Used to load full post details on the post detail screen.
     *
     * @param postId The Firestore document ID
     * @return Result containing the Post, or null if not found
     */
    override suspend fun getPost(postId: String): Result<Post?> = runCatching {
        val snapshot = postsCollection.document(postId).get().await()
        snapshot.toObject(Post::class.java)?.copy(id = snapshot.id)
    }
}

