/**
 * CarRepository.kt
 * ==================
 * This file defines the CarRepository interface - the contract for car data operations.
 *
 * KEY CONCEPTS FOR BEGINNERS:
 * ---------------------------
 * 1. CRUD OPERATIONS: This interface covers all CRUD operations:
 *    - Create: addCar()
 *    - Read: observeCars(), getCar()
 *    - Update: updateCar(), updateAvailability(), updatePricing()
 *    - Delete: deleteCar()
 *
 * 2. FLOW FOR REAL-TIME UPDATES: observeCars() returns a Flow, which means
 *    the UI automatically updates when cars are added/modified/deleted
 *    in Firestore by any user or admin.
 *
 * 3. SINGLE RESPONSIBILITY: This interface ONLY deals with car data.
 *    Booking logic is in BookingRepository, auth in AuthRepository, etc.
 */
package com.example.drivewise.domain.repository

import com.example.drivewise.domain.model.Car
import kotlinx.coroutines.flow.Flow

/**
 * Contract for car fleet management operations.
 *
 * Implemented by FirebaseCarRepository.
 * Used by CarViewModel to manage the rental car fleet.
 */
interface CarRepository {

    /**
     * Observes all cars in real-time.
     *
     * Returns a Flow that emits the current list of cars whenever:
     * - Initial data is loaded
     * - A car is added
     * - A car is updated
     * - A car is deleted
     *
     * The list is sorted by createdAt (newest first).
     *
     * @return Flow emitting List<Car> on every change
     */
    fun observeCars(): Flow<List<Car>>

    /**
     * Fetches a single car by its ID.
     *
     * @param carId The Firestore document ID of the car
     * @return Result containing the Car, or null if not found
     */
    suspend fun getCar(carId: String): Result<Car?>

    /**
     * Adds a new car to the fleet.
     *
     * The car ID will be auto-generated by Firestore.
     *
     * @param car The car data to add (id field will be overwritten)
     * @return Result.success if added, Result.failure with exception if not
     */
    suspend fun addCar(car: Car): Result<Unit>

    /**
     * Updates an existing car's information.
     *
     * Replaces the entire document with the new car data.
     *
     * @param car The car with updated fields (must have valid id)
     * @return Result.success if updated, Result.failure with exception if not
     */
    suspend fun updateCar(car: Car): Result<Unit>

    /**
     * Deletes a car from the fleet.
     *
     * WARNING: This is permanent! Consider implications for existing bookings.
     *
     * @param carId The ID of the car to delete
     * @return Result.success if deleted, Result.failure with exception if not
     */
    suspend fun deleteCar(carId: String): Result<Unit>

    /**
     * Updates only the availability status of a car.
     *
     * Convenience method - faster than updating the whole car document.
     * Used when admin toggles availability without changing other fields.
     *
     * @param carId The car's document ID
     * @param available Whether the car should be available for booking
     * @return Result.success if updated successfully
     */
    suspend fun updateAvailability(carId: String, available: Boolean): Result<Unit>

    /**
     * Updates only the daily rental price of a car.
     *
     * Convenience method for quick price adjustments.
     *
     * @param carId The car's document ID
     * @param newPrice The new daily rental price
     * @return Result.success if updated successfully
     */
    suspend fun updatePricing(carId: String, newPrice: Double): Result<Unit>
}

