/**
 * PostsRepository.kt
 * ===================
 * This file defines the PostsRepository interface - the contract for post operations.
 *
 * KEY CONCEPTS FOR BEGINNERS:
 * ---------------------------
 * 1. SIMPLE INTERFACE: Posts are simpler than bookings - just create and read.
 *    No update or delete in this version (could be added later).
 *
 * 2. REAL-TIME POSTS: observePosts() returns a Flow, so when an admin
 *    creates a new post, all users see it immediately without refreshing.
 */
package com.example.drivewise.domain.repository

import com.example.drivewise.domain.model.Post
import kotlinx.coroutines.flow.Flow

/**
 * Contract for promotional/news post operations.
 *
 * Implemented by FirebasePostsRepository.
 * Used by PostsViewModel to manage posts.
 */
interface PostsRepository {

    /**
     * Observes all posts in real-time.
     *
     * Posts are sorted by createdAt (newest first).
     * Both admins and clients can view posts.
     *
     * @return Flow emitting list of posts whenever posts change
     */
    fun observePosts(): Flow<List<Post>>

    /**
     * Creates a new post.
     *
     * Only admins should call this (enforced at UI level).
     * The post ID is auto-generated by Firestore.
     *
     * @param post The post to create (id field will be auto-generated)
     * @return Result.success if created successfully
     */
    suspend fun createPost(post: Post): Result<Unit>

    /**
     * Fetches a single post by ID.
     *
     * Used to show post details on a detail screen.
     *
     * @param postId The Firestore document ID
     * @return Result containing the Post, or null if not found
     */
    suspend fun getPost(postId: String): Result<Post?>
}

